### PR TITLE
Rename "Web" to "Browser"

### PR DESCRIPTION
**Pull request by saicheems**

### CODE REVIEW

**Comment by tcoffee-google** [comment]
+1

**Comment by saicheems** [comment]
My only hesitation against "JavaScript (Browser)" is that the tab name is too long. The next longest tab name would be "Python". I think this would look weird, but not sure how you feel about it.

**Comment by tcoffee-google** [comment]
My position has always been that "JavaScript" is the best choice. I've never heard anyone say that they program in Browser.

**Comment by saicheems** [comment]
I realize there's little chance of 100% agreement, but given that there's internal consensus on "Browser", can we continue with it? Considering the original naming was "Web"... it is an improvement.

**Comment by vchudnov-g** [comment]
It's your call, @saicheems 

From where I stand, the number one priority by far is consistency across pages on our doc sites. After that, I would say it's important (but less so) to have consistency in the tab naming, which is why I prefer "JavaScript (Browser)" from among the options favored by the team who asked for this. But you're right that "Browser" is no worse than "Web" here.

With either of these two options, this pr lgtm.

**Comment by tcoffee-google** [comment]
I concur with all the above.

**Comment by saicheems** [comment]
Will roll with this, and come back if there's further complaints. We're only starting with one API now anyway, so I hope it won't be a big issue.

**Comment by vchudnov-g** [comment]
Sure, but we should republish the samples for the rolled-out APIs for consistency.

**Comment by saicheems** [comment]
We haven't rolled any out with JS have we?

**Comment by saicheems** [comment]
(since it's disabled by default, no APIs show JS samples right now)

**Comment by vchudnov-g** [comment]
Oh, I think you're right. We never did manage to publish anything with JS earlier. Nm.

**Pull request merged**
